language: cpp

sudo: required

compiler:
  - clang
  - gcc

env:
  - 'BUILD_TYPE=Release'
  - 'BUILD_TYPE=Debug'
  
before_script:
  - sudo apt-get update
  - sudo apt install -y libmysqlclient-dev
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_MYSQL=ON ..
  
script: make -j2
