language: cpp

compiler:
  - clang
  - gcc

env:
  - 'BUILD_TYPE=Release'
  - 'BUILD_TYPE=Debug'
  
before_script:
  - sudo apt-get install libuv1-dev libmariadb-dev
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  
script: make -j2
