# Specify version format
version: "{build}"

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

os:
  - Visual Studio 2017
  - Visual Studio 2015

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Release
  - Debug

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - git config --global core.autocrlf input
  
# clone directory
clone_folder: C:\projects\GameSpyEmulator

# branches to build
#branches:
  # whitelist
  #only: 
    #- master
    #- develop

skip_commits:
  files:
    - docs/*

# Maximum number of concurrent jobs for the project
max_jobs: 1

# scripts that run after cloning repository
install:
  - cmd: cd C:\projects\GameSpyEmulator
  - cmd: git submodule update --init --recursive

# scripts to run before build
before_build:
  - cmd: cd C:\projects\GameSpyEmulator
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%GENERATOR%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%GENERATOR% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration%  ..
  
build:
  project: C:\projects\GameSpyEmulator\build\GameSpyEmulator.sln # path to Visual Studio solution or project
  parallel: true                             # enable MSBuild parallel builds
  verbosity: minimal                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off
